name: Node CI

on:
  push:
    branches:
      - master
      - feature/*
      - release/*
      - fix/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: npm install, build and test
        run: |
          bun install
          bun run build --if-present
          bun run test
        env:
          CI: true
  pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Produce pkg - lts
        run: |
          sudo bun install -g pkg
          bun install
          bun run pkg -t node18-linux,node18-win,node18-mac package.json --out-path dist
      - name: Test pkg
        run: |
          chmod +x dist/cdxgen*
          ./dist/cdxgen-linux -v
          ./dist/cdxgen-linux . -p
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
